# Site settings
title: "TheIGuy"
title_separator: "|"
subtitle: "Developer & Designer"
description: "CSM, Tech Support Manager & Industrial Designer"
url: "https://theiguy.ca"
baseurl: ""

# Theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Author
author:
  name: "TheIGuy"
  avatar: "/assets/images/bio-photo.jpg" # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio: "CSM, Tech Support Manager & Industrial Designer"
  location: "EMEA"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/oneguy1"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/oneguy1"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Navigation
main:
  - title: "Portfolio"
    url: /portfolio/
  - title: "Code Snippets"  
    url: /code-snippets/
  - title: "Industrial Design"
    url: /design/
  - title: "My App"
    url: /app/
  - title: "About"
    url: /about/
